### ISSUE TITLE
Features/Research Connecting Gateway and FrontEnd

### ISSUE THREAD

**Issue by kimlisa** [faraonc/hwsc-gateway-svc#34]
## Description
As a developer, I want to decouple hwsc-gateway-svc from hwsc-frontend-svc either using a distribution folder or using gRPC.

## Definitions of Done

- Minimal working example

**Comment by faraonc** [comment]
1 possible solution with bash script integration, [link](https://github.community/t5/How-to-use-Git-and-GitHub/How-can-I-download-a-specific-folder-from-a-GitHub-repo/m-p/88#M20)

**Comment by kimlisa** [comment]
@faraonc I think this is what we want, [how-you-can-do-continuous-delivery-with-vue-docker-and-azure](url)

Article is quite long, so I shall save thorough reading on another day b/c I only kinda know dockers in theory... I have no idea how to go setting up one.

**Comment by kimlisa** [comment]
Quote from the link I provided above:

> For our purposes, “Continuous Delivery” means that the process of building and deploying the site is completely automated. Here’s how that looks in real life:
> 
> Developer checks code into Github master branch
> Build server pulls code from Github
> Build server runs a build (npm script)
> Build server creates a Docker container
> Build server pushes Docker container to registry
> Burke finds the source of broccoli smell in his office
> Website pulls in updated container

**Comment by faraonc** [comment]
sounds like what we are trying to do in general for deployment

**Comment by faraonc** [comment]
i will read more about this later
