### ISSUE TITLE
Feature/hwsc-file-svc Dependency or Package Management

### ISSUE THREAD

**Issue by faraonc** [faraonc/hwsc-gateway-svc#38]
## Description
As a developer, I want to be able to use pip to manage my hwsc-file-svc dependencies.

## Definitions of Done
- A text file containing pip dependencies needed to install

**Comment by yeseulan** [comment]
Useful link: https://packaging.python.org/tutorials/managing-dependencies/

**Comment by yeseulan** [comment]
https://medium.com/python-pandemonium/better-python-dependency-and-package-management-b5d8ea29dff1

**Comment by faraonc** [comment]
https://pypi.org/project/pipenv/
