### ISSUE TITLE
Feature/hwsc-user-svc Proto Contract

### ISSUE THREAD

**Issue by faraonc** [faraonc/hwsc-gateway-svc#72]
## Description
As a user, I want my profile and document managed.

## Definitions of Done
- [x] proto in API Blocks
- [x] compiled pb
- [x] modified [script](https://github.com/faraonc/hwsc-api-blocks/blob/master/generate_int_proto.sh)
- [x]  README.md

**Comment by faraonc** [comment]
https://github.com/faraonc/hwsc-gateway-svc/issues/63

**Comment by faraonc** [comment]
Let us say Chrome wants to add a new document. At this point Chrome knows the user's uuid already. 
1. The user fills up the form in the website.
2. Grabs the fields in the form and make a [Document](https://github.com/faraonc/hwsc-api-blocks/blob/master/lib/document.proto) object. ``image_urls_map, audio_urls_map, video_urls_map, & file_urls_map`` are not filled up because there is no means of generating duid and fuids in the browser, therefore we have to send lists of urls.
3. Chrome calls app-gateway-svc's ``AddDocument()`` with the following
```
message AppGatewayRequest{
    hwsc.User user = N; //this is not a complete User object, it may only have uuid
    hwsc.Document doc = N;
    repeated string image_urls = N;
    repeated string audio_urls = N;
    repeated string video_urls = N;
    repeated string file_urls = N;
}
```
4. app-gateway-svc calls document-svc's CreateDocument() which returns the newly Created Document with a now generated duid and fuids.
5. app-gateway-svc calls user-svc's GetUser, which returns a full User object A with password as empty string.
6. app-gateway-svc calls modifies the User object A, and adds the DUID in the in it.
7. app-gateway-svc calls user-svc's UpdateUser, which returns a full User object with password as empty string.
8.  
    1.  OPTION 1 - app-gateway-svc returns 2 objects (updated User and updated Document) to Chrome
    2. OPTION 2 - app-gateway-svc calls document-svc ListUserDocumentCollection, returns a list of user documents.
9. Chrome renders page.

**Comment by kimlisa** [comment]
TODO: create Epic for DeleteDocuments, starting with CRUD operations

similar to:
https://github.com/faraonc/hwsc-gateway-svc/issues/74
